### ISSUE TITLE
官方200525语言包会提示语言文件为旧版本，无法使用

### ISSUE THREAD

**Issue by le-matin** [hr157/QTTabBar_zh-CN#1]
试过一下两种方法，均无法使用该语言文件包
1.先安装 1038包，再UPdate 1042包，无法使用该语言文件包，
2.直接安装1042，无法使用该语言文件包

**Comment by hr157** [comment]
语言包已更新
<Version_QTTabBar>
DevBuild: 2020/5/25 0:06:02
</Version_QTTabBar>

<DateModified>
06/15/2021
</DateModified>
